FROM python:3.11-slim

WORKDIR /app-agent

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./requirements.txt /app-agent/
COPY ./my_agent  ./my_agent/


EXPOSE 8000

CMD ["adk", "web", "--port", "8000", "--host", "0.0.0.0"]
