#GENAI Toolbox

name: agent-app

services:
  #agent-service:
   # image: mi-agente-app:latest
    #container_name: agent-service
   # ports:
    #- "8000:8000"
    #networks:
     # - agent-network

  agent-database:
    image: mongo:latest
    container_name: agent-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - agent-network

  mongo-mcp:
    image: mongodb/mongodb-mcp-server:latest
    container_name: mongo-mcp
    environment:
      MDB_MCP_READ_ONLY: true
      MDB_MCP_TRANSPORT: "http"
      MDB_MCP_HTTP_HOST: "0.0.0.0"
      MDB_MCP_HTTP_PORT: 3000
      MDB_MCP_CONNECTION_STRING: "mongodb://admin:password@agent-database:27017"
    ports:
      - "3000:3000"
    #networks:
     # - agent-network
    depends_on:
      - agent-database

networks:
  agent-network:

volumes:
  mongo-data:
    driver: local
